<?php

namespace AppBundle\Repository;

/**
 * ChildsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildsRepository extends \Doctrine\ORM\EntityRepository
{
	public function nextId($id,$sede,$lista,$telefonero){

		$em = $this->getEntityManager(); 
		$qb = $em->createQueryBuilder();
		$qb->select('c')
		   ->from('AppBundle:Childs', 'c')
		   ->where('c.type = :first AND c.id > :id AND c.sede = :sede ')
		   //->andWhere('c.id > :id')
		   ->setParameter('id', $id)
		   ->setParameter('sede', $sede)
		   ->setParameter('first', $lista)
		   ->setMaxResults(1)
		   ->orderBy('c.id', 'ASC');
		   if ($telefonero) {
		   	$qb->andWhere('c.telefonero = :telefonero')
		   	->setParameter('telefonero',$telefonero);
		   }
	  $query = $qb->getQuery();
	  return $query->getResult();
	}

	public function backId($id,$sede,$lista,$telefonero){

		$em = $this->getEntityManager(); 
		$qb = $em->createQueryBuilder();
		$qb->select('c')
		   ->from('AppBundle:Childs', 'c')
		   ->where('c.type = :first AND c.id < :id AND c.sede = :sede ')
		   //->andWhere('c.id > :id')
		   ->setParameter('id', $id)
		   ->setParameter('sede', $sede)
		   ->setParameter('first', $lista)
		   ->setMaxResults(1)
		   ->orderBy('c.id', 'DESC');
		   if ($telefonero) {
		   	$qb->andWhere('c.telefonero = :telefonero')
		   	->setParameter('telefonero',$telefonero);
		   }
	  $query = $qb->getQuery();
	  return $query->getResult();
	}
}
