<?php

namespace AppBundle\Repository;

/**
 * ChildsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildsRepository extends \Doctrine\ORM\EntityRepository
{
}
