<?php

namespace AppBundle\Repository;

/**
 * datesChildsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class datesChildsRepository extends \Doctrine\ORM\EntityRepository
{
}
