<?php

namespace AppBundle\Repository;

/**
 * EstrellaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstrellaRepository extends \Doctrine\ORM\EntityRepository
{
}
