<?php

namespace AppBundle\Repository;

/**
 * InstituteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstituteRepository extends \Doctrine\ORM\EntityRepository
{
}
