<?php

namespace AppBundle\Repository;

/**
 * StarsChildsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarsChildsRepository extends \Doctrine\ORM\EntityRepository
{
}
