<?php

namespace AppBundle\Repository;

/**
 * TelefoneroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefoneroRepository extends \Doctrine\ORM\EntityRepository
{
}
